policy: "CnnPolicy"
use_reward_predictor: True
exploration_params:
  kind: "NovelD"
  intrinsic_reward_integration: 0.85
  policy_weight: 1.0
  reward_scale: 0.01
  weight: 0.2
  alpha: 0.5
  count_norm: True
  model_params:
    latent_dim: 128