name: reactive_exploration
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2022.3.29
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - cryptography=36.0.0
  - cudatoolkit=11.3.1
  - freetype=2.10.4
  - idna=3.3
  - intel-openmp=2021.4.0
  - jpeg=9d
  - libpng=1.6.37
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp=1.2.2
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numpy-base=1.21.5
  - openssl=1.1.1n
  - pillow=9.0.1
  - pip=21.2.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.12
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - requests=2.27.1
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.2
  - tk=8.6.11
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - typing_extensions=4.1.1
  - tzdata=2022a
  - urllib3=1.26.8
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - absl-py==0.10.0
    - antlr4-python3-runtime==4.8
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - array2gif==1.0.4
    - asttokens==2.0.5
    - astunparse==1.6.3
    - atari-py==0.2.9
    - attrs==21.4.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.0
    - cachetools==5.0.0
    - cloudpickle==1.3.0
    - cycler==0.11.0
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.4
    - dm-tree==0.1.7
    - docker-pycreds==0.4.0
    - entrypoints==0.4
    - enum34==1.1.10
    - executing==0.8.3
    - fastjsonschema==2.15.3
    - flatbuffers==2.0
    - fonttools==4.32.0
    - future==0.18.2
    - gast==0.5.3
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.6.5
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - googleapis-common-protos==1.56.0
    - grpcio==1.44.0
    - gym==0.17.3
    - h5py==3.6.0
    - hydra-core==1.1.2
    - importlib-metadata==4.11.3
    - ipykernel==6.13.0
    - ipython==8.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jsonschema==4.5.1
    - jupyter==1.0.0
    - jupyter-client==7.3.1
    - jupyter-console==6.4.3
    - jupyter-core==4.10.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.0
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.2
    - libclang==13.0.0
    - markdown==3.3.6
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - nbclient==0.6.3
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - notebook==6.4.11
    - numpy==1.22.3
    - oauthlib==3.2.0
    - omegaconf==2.1.2
    - opencv-python==4.5.5.64
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.4.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pickleshare==0.7.5
    - prometheus-client==0.14.1
    - promise==2.3
    - prompt-toolkit==3.0.29
    - protobuf==3.20.0
    - psutil==5.9.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyglet==1.5.0
    - pygments==2.12.0
    - pyparsing==3.0.8
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pywin32==304
    - pywinpty==2.0.5
    - pyyaml==6.0
    - pyzmq==23.0.0
    - qtconsole==5.3.0
    - qtpy==2.1.0
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scipy==1.8.1
    - seaborn==0.11.2
    - send2trash==1.8.0
    - sentry-sdk==1.5.10
    - setproctitle==1.2.3
    - shortuuid==1.0.8
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - stable-baselines==2.10.2
    - stable-baselines3==0.10.0
    - stack-data==0.2.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.5
    - tensorflow==2.8.0
    - tensorflow-datasets==4.0.1
    - tensorflow-estimator==2.4.0
    - tensorflow-gcs-config==2.4.0
    - tensorflow-hub==0.11.0
    - tensorflow-io-gcs-filesystem==0.24.0
    - tensorflow-metadata==0.27.0
    - tensorflow-probability==0.12.1
    - termcolor==1.1.0
    - terminado==0.15.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - tornado==6.1
    - tqdm==4.64.0
    - traitlets==5.2.1.post0
    - wandb==0.12.15
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.6.0
    - wrapt==1.14.0
    - zipp==3.8.0
