name: reactive_exploration
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.2.1
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - cryptography=36.0.0
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - freetype=2.11.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.3
  - intel-openmp=2021.4.0
  - jpeg=9d
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - openh264=2.1.1
  - openssl=1.1.1n
  - pillow=9.0.1
  - pip=21.2.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.7
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - readline=8.1.2
  - requests=2.27.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.38.0
  - tk=8.6.11
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - typing_extensions=4.1.1
  - tzdata=2021e
  - urllib3=1.26.8
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==0.10.0
    - antlr4-python3-runtime==4.8
    - anyio==3.6.1
    - arch==5.0.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - array2gif==1.0.4
    - asttokens==2.0.5
    - astunparse==1.6.3
    - attrs==21.4.0
    - backcall==0.2.0
    - beautifulsoup4==4.10.0
    - bleach==4.1.0
    - cachetools==5.0.0
    - click==8.1.2
    - cloudpickle==1.3.0
    - cycler==0.11.0
    - debugpy==1.5.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.4
    - dm-tree==0.1.6
    - docker-pycreds==0.4.0
    - entrypoints==0.4
    - executing==0.8.3
    - filelock==3.6.0
    - flatbuffers==2.0
    - fonttools==4.31.2
    - future==0.18.2
    - gast==0.5.3
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.6.2
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - googleapis-common-protos==1.56.0
    - grpcio==1.44.0
    - gym==0.17.3
    - h5py==3.6.0
    - hydra-core==1.1.1
    - importlib-metadata==4.11.3
    - ipykernel==6.9.2
    - ipython==8.1.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter==1.0.0
    - jupyter-client==7.1.2
    - jupyter-console==6.4.3
    - jupyter-core==4.9.2
    - jupyter-server==1.17.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.1.0
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.0
    - libclang==13.0.0
    - llvmlite==0.38.0
    - markdown==3.3.6
    - markupsafe==2.1.1
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - nbclient==0.5.13
    - nbconvert==6.4.4
    - nbformat==5.2.0
    - nest-asyncio==1.5.4
    - notebook==6.4.10
    - notebook-shim==0.1.0
    - numba==0.55.1
    - oauthlib==3.2.0
    - omegaconf==2.1.1
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.4.1
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathtools==0.1.2
    - patsy==0.5.2
    - pexpect==4.8.0
    - pfrl==0.3.0
    - pickleshare==0.7.5
    - prometheus-client==0.13.1
    - promise==2.3
    - prompt-toolkit==3.0.28
    - property-cached==1.6.4
    - protobuf==3.19.4
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyglet==1.5.0
    - pygments==2.11.2
    - pyparsing==3.0.7
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - pyzmq==22.3.0
    - qtconsole==5.2.2
    - qtpy==2.0.1
    - requests-oauthlib==1.3.1
    - rliable==1.0.7
    - rsa==4.8
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - seaborn==0.11.2
    - send2trash==1.8.0
    - sentry-sdk==1.5.8
    - setproctitle==1.2.2
    - shortuuid==1.0.8
    - sklearn==0.0
    - smmap==5.0.0
    - sniffio==1.2.0
    - soupsieve==2.3.1
    - stable-baselines3==0.10.0
    - stack-data==0.2.0
    - statsmodels==0.13.2
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.5
    - tensorflow==2.8.0
    - tensorflow-datasets==4.0.1
    - tensorflow-estimator==2.4.0
    - tensorflow-gcs-config==2.4.0
    - tensorflow-hub==0.11.0
    - tensorflow-io-gcs-filesystem==0.24.0
    - tensorflow-metadata==0.27.0
    - tensorflow-probability==0.12.1
    - termcolor==1.1.0
    - terminado==0.13.3
    - testpath==0.6.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - threadpoolctl==3.1.0
    - tornado==6.1
    - tqdm==4.63.0
    - traitlets==5.1.1
    - wandb==0.12.11
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.3.2
    - werkzeug==2.0.3
    - widgetsnbextension==3.6.0
    - wrapt==1.14.0
    - yaspin==2.1.0
    - zipp==3.7.0
