cartpole_dicts:
- modulo_theta: true
  reset_pole_on_drop: true
  rew_theta_c: 0.003472222222222222
  rew_xc: 0.08680555555555555
  reward_function: variable
  stop_at_x_threshold: true
- length: 1.1
  masscart: 3.2
  modulo_theta: true
  reset_pole_on_drop: true
  rew_theta_c: 0.003472222222222222
  rew_xc: 0.08680555555555555
  reward_function: variable
  stop_at_x_threshold: true
env_name: InfHCartPole-v1
soft_horizon: 1e4
use_vision_wrapper: false
