# directory creation is handled by Hydra
hydra:
  sweep:
    dir: ../outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}/seed=${seed}
  run:
    dir: ../outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    config:
      override_dirname:
        exclude_keys:
          - seed
          - store_trajectory
          - start_recording
          - stop_recording

# defaults for variable components --> agent_params, env_params
defaults:
  - _self_
  - agent_params: icm_mlp
  - env_params: cartpole_length_mass

experiment_name: PPO_Cartpole_Length_Mass-v1
seed: 1
device_str: 'cuda:0'
steps: 1e6
use_wandb: True
store_trajectory: False
start_recording: 0
stop_recording: -1

run_params:
  log_dir: './double_length_mass'
  save_dir: './double_length_mass'
  with_timestamp: False

callback_params:
  save_freq: 1e7
